#!/bin/bash

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli c | grep enp5s0 | awk '{print ($1)}')

if [ $status ] ; then
	icon="󰤭"
	text=""
	col="#9D937E"

else
	icon="󰤨"
	text=" ${essid}"
	col="#A7C080"
fi

if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi
