# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
# Theme and plugins
ZSH_THEME="robbyrussell"
plugins=(git
	fzf
	zsh-autosuggestions)

#Colors of directories and stuff
LS_COLORS=$LS_COLORS:'di=0;32:'  #to green
export LS_COLORS

# Sourcing the zshell
source $ZSH/oh-my-zsh.sh

# fuzzyfinder 
export FZF_DEFAULT_COMMAND="find . $HOME"
export FZF_DEFAULT_OPTS="--height=40% --margin=2%,2%,2%,2% --layout=reverse-list
--border=double --info=inline --prompt='→ ' --pointer='→' --marker='♡'
--header='CTRL-c or ESC to quit'
--color='dark,fg:#dcd1bb,fg+:#DBBC7F,prompt:#64816d,pointer:#7FBBB3'"

export FZF_CTRL_T_COMMAND="find $HOME -type f"
export FZF_ALT_C_COMMAND="find $HOME -type d"
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"
# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
--height=60%
  --preview 'bat -n --color=always {} --theme=ansi'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
# ALIASES
# Usual commands
alias ls='lsd --color=auto'
## Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
# LibreOffice
alias writer='env GTK_THEME=Adwaita:light libreoffice --writer &'
alias excel='env GTK_THEME=Adwaita:light libreoffice --calc &'
alias vim='nvim'
alias qtileconfig="cd ~/.config/qtile/ && vim config.py"
alias autostart='cd ~/.config/qtile/ && vim autostart.sh'
alias termconfig='cd ~/.config/alacritty/ && vim alacritty.yml'
alias ezsh='vim ~/.zshrc'
alias picomconfig='cd ~/.config/qtile/ && vim picom.conf'
# Battery for notebook config
alias ecomode='sudo tlp bat'
alias acmode='sudo tlp ac'
# Change wallpaper
alias chwall='feh --bg-fill --randomize ~/Pictures/.wallpapers/*'
# Which vga is running 
alias whichvga="/usr/local/bin/arcolinux-which-vga"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#A7C080,bg=#1C1F20"
